apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: vkvbwzkxz-java-springboot
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:66aecb00cdb90c64f6872272bb575cbe89d3a993@sha256:f8ba7cb02452920bfd50c05d59cab7cd957e9579d73962cc6e4cc68e6f9212da
          name: container-image
